version: '3'
services:
  rating-service:
    image: pankajsharma151290/movie-ratings:1.0.0
    environment:
      - SERVER_PORT=8280
      - MONGO_DB_HOST=ratings-mongo
      - MONGO_DB_PORT=27017
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
      - CONFIG_SERVER_HOST=could-config-server
      - CONFIG_SERVER_PORT=8888
    depends_on:
      - ratings-mongo
      - eureka-server
      - could-config-server
    ports:
    - 8280:8280
    networks:
      - spring-cloud-network

  ratings-mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - mongodata:/data/db
    networks:
      - spring-cloud-network

  eureka-server:
    image: pankajsharma151290/eureka-server:1.0.0
    ports:
      - 8761:8761
    environment:
      - SERVER_PORT=8761
    networks:
      - spring-cloud-network

  could-config-server:
    image: pankajsharma151290/cloud-config-server:1.0.0
    environment:
      - SERVER_PORT=8888
    ports:
      - 8888:8888
    networks:
      - spring-cloud-network

volumes:
    mongodata:
      external: true

networks:
  spring-cloud-network:
    driver: bridge

