version: '3'
services:
  movie-info-service:
    image: movie-info
    environment:
      - SERVER_PORT=8180
      - EUREKA_HOST=eureka-server
      - EUREKA_PORT=8761
      - CONFIG_SERVER_HOST=could-config-server
      - CONFIG_SERVER_PORT=8888
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - eureka-server
      - redis
      - could-config-server
    ports:
      - 8180:8180
    networks:
      - spring-cloud-network

  eureka-server:
    image: eureka-server
    ports:
      - 8761:8761
    environment:
      - SERVER_PORT=8761
    networks:
      - spring-cloud-network

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - spring-cloud-network

  could-config-server:
    image: could-config-server
    environment:
      - SERVER_PORT=8888
    ports:
      - 8888:8888
    networks:
      - spring-cloud-network

volumes:
  redis-data:
    external: true

networks:
  spring-cloud-network:
    driver: bridge

