#------------
#Eureka Server service
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service2
  labels:
    app: eureka-server-service2
    tier: backend
spec:
  selector:
    app: eureka-discovery-server
  type: NodePort
  ports:
   - nodePort: 31001
     port: 8761
     targetPort: 8761