#------------
#Eureka Server service
apiVersion: v1
kind: Service
metadata:
  name: eureka-discovery-server
  labels:
    app: eureka-discovery-server
    tier: backend
spec:
  selector:
    app: eureka-discovery-server
  type: ClusterIP
  ports:
   - port: 8761
     targetPort: 8761