#Service
apiVersion: v1
kind: Service
metadata: 
  name: movie-ratings-service
  labels:
    app: movie-ratings
    tier: backend
spec:
  selector:
    app: movie-ratings
  type: NodePort
  ports:
    - nodePort: 31000
      port: 8280
      targetPort: 8280
  