apiVersion: v1
kind: Service
metadata:
  name: movie-ratings-db
  labels:
    app: movie-ratings-db
    tier: backend
spec:
  selector:
    app: movie-ratings-db
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017