#ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-rs
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx-app
    matchExpressions:
     - {key: tier, operator: In, values: [FE]}
  template:
    metadata:
      name: nginx-pod
      labels: 
        app: nginx-app
        tier: FE		
    spec:
      containers:
      - name: nginx-contoller
        image: nginx
        ports:
        - containerPort: 80